###Hämta alla bokningar
GET http://localhost:5184/api/booking
Content-Type: application/json



###Hämta en bokning (id = 1)
GET http://localhost:5184/api/booking/1
Content-Type: application/json


### Skapa ny bokning
POST http://localhost:5184/api/booking
Content-Type: application/json

{
  "userId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "resourceId": 1,
  "startTime": "2025-09-06T10:00:00",
  "endTime": "2025-09-06T11:00:00",
  "status": "Confirmed"
}

### Uppdatera bokning (id = 1)
PUT http://localhost:5184/api/booking/1
Content-Type: application/json

{
  "userId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "resourceId": 2,
  "startTime": "2025-09-06T12:00:00",
  "endTime": "2025-09-06T13:00:00",
  "status": "Confirmed"
}

### Radera bokning (id = 2)
DELETE http://localhost:5184/api/booking/2
Content-Type: application/json
